ccflags-y += -I$(src)			# needed for trace events

obj-$(CONFIG_ANDROID_BINDER_IPC)	+= binder.o
obj-$(CONFIG_ANDROID_BINDER_IPC)	+= binder1.o
obj-$(CONFIG_ANDROID_BINDER_IPC)	+= binder2.o
obj-$(CONFIG_ANDROID_BINDER_IPC)	+= binder3.o
obj-$(CONFIG_ANDROID_BINDER_IPC)	+= binder4.o
obj-$(CONFIG_ANDROID_BINDER_IPC)	+= binder5.o
obj-$(CONFIG_ANDROID_BINDER_IPC)	+= binder6.o
obj-$(CONFIG_ANDROID_BINDER_IPC)	+= binder7.o
obj-$(CONFIG_ANDROID_BINDER_IPC)	+= binder8.o
obj-$(CONFIG_ANDROID_BINDER_IPC)	+= binder9.o
obj-$(CONFIG_ANDROID_BINDER_IPC)	+= binder10.o
obj-$(CONFIG_ANDROID_BINDER_IPC)	+= binder11.o
obj-$(CONFIG_ANDROID_BINDER_IPC)	+= binder12.o
obj-$(CONFIG_ANDROID_BINDER_IPC)	+= binder13.o
obj-$(CONFIG_ANDROID_BINDER_IPC)	+= binder14.o
obj-$(CONFIG_ANDROID_BINDER_IPC)	+= binder15.o
obj-$(CONFIG_ANDROID_BINDER_IPC)	+= binder16.o
obj-$(CONFIG_ANDROID_BINDER_IPC)        += binder17.o
obj-$(CONFIG_ANDROID_BINDER_IPC)        += binder18.o
obj-$(CONFIG_ANDROID_BINDER_IPC)        += binder19.o
obj-$(CONFIG_ANDROID_BINDER_IPC)        += binder20.o

