ccflags-y += -I$(src)			# needed for trace events

obj-$(CONFIG_ANDROID_BINDER_IPC)	+= binder.o
obj-$(CONFIG_ANDROID_BINDER_IPC)        += binder1.o
obj-$(CONFIG_ANDROID_BINDER_IPC)        += binder2.o
